### ISSUE TITLE
Newly introduced AttributeError when using colander.deferred with callables.

### ISSUE THREAD

**Issue by thruflo** [Pylons/colander#141]
Hey, pull request #134 raises an AttributeError when passing callables to
colander.deferred, i.e.: colander.deferred now expects its arg to be a
function, whereas before it could be an instance with a `__call__` method.

Is this intended?  Or is it intended that the decorator continue to work
with arbitrary callables?

For example, I have code (which worked fine in colander 1.0a5) like:

```
product_widget = colander.deferred(ModelWidget(Product))
```

Where `ModelWidget` is along the lines of:

```
class ModelWidget(object):
    def __call__(self, node, kw):
        # returns a widget with values populated from the database
```

Updating to 1.0b1 now raises an exception at import time:

```
14:55:12 web.1      |   File "XXX", line XXX, in <module>
14:55:12 web.1      |     product_widget = colander.deferred(ModelWidget(Product))
14:55:12 web.1      |   File "XXX/lib/python2.7/site-packages/colander/__init__.py", line 2128, in __init__
14:55:12 web.1      |     functools.update_wrapper(self, wrapped)
14:55:12 web.1      |   File "/usr/local/Cellar/python/2.7.2/lib/python2.7/functools.py", line 33, in update_wrapper
14:55:12 web.1      |     setattr(wrapper, attr, getattr(wrapped, attr))
14:55:12 web.1      | AttributeError: 'ModelWidget' object has no attribute '__name__'
```

Looking at the [functools docs](http://docs.python.org/2/library/functools.html#functools.update_wrapper) it seems pretty clear that `wrapped` needs to
be a function with a `__name__` attribute.
